services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    network_mode: host
    privileged: true

    environment:
      TZ: ${TZ}

    volumes:
      - ./config:/config
      - /run/dbus:/run/dbus:ro

    mem_limit: ${HOMEASSISTANT_MEM_LIMIT}
